#!/bin/csh -f
############################


set PROG=`basename $0`
 if ( $#argv < 3 ) then
  echo
  echo "Usage: $PROG <outname> <intput list file> <split number:20> "
  exit
endif

setenv comment $1
setenv INPUT $2
setenv NLINE $3
#################################
# Output file locations
#################################
setenv Main_DIR     `pwd`
setenv DoWhat       dijet
setenv oname        $comment
setenv Disk         `pwd`
setenv OUT_ERRORS   $Disk/outputs/${oname}/errors
setenv Out_DIR      $Disk/outputs/${oname}/data
setenv LOG_DIR      $Disk/outputs/${oname}/logs
setenv INPUT_DIR      $Disk/outputs/${oname}/inputs
#################################
# Need for serial job in sepeli(pbs)
#################################
setenv noFileToRun 50
#################################

mkdir -p $OUT_ERRORS
mkdir -p $Out_DIR
mkdir -p $LOG_DIR
mkdir -p $INPUT_DIR
split -l $NLINE -d $INPUT $INPUT_DIR/input
echo "TEST"
setenv noFileToRun `find $INPUT_DIR -type f | grep input | wc -l`
echo $noFileToRun

#################################
# Runlist to scan
#################################

# simplify this !!! 
cat << EOF > exec_jtkt_$comment
#!/bin/csh -f
cd $Main_DIR
setenv what  $DoWhat
setenv sedN  100000
setenv iseg \$SLURM_ARRAY_TASK_ID
@ iseg2 = \$iseg - 1
@ sedN = \${sedN} + \${iseg}
setenv outfile  $Out_DIR/$comment-\$sedN.root 
setenv Log      $LOG_DIR/$comment-\$sedN.log
setenv pySetting      $LOG_DIR/$comment-\$sedN.config
./\${what} \$INPUT_DIR/input\`printf "%02d" \$iseg2 \` \$outfile cardAlice_pp.input hadron hadron  |& grep -v "Warning in <TVector3::PseudoRapidity>:" >& \$Log
cd $Main_DIR
EOF
#\${what} \$outfile \$sedN 5000000 >& \$Log
chmod +x exec_jtkt_$comment
	#qsub -a 201008240200 -V -t 1-$noFileToRun -S /bin/tcsh -r y -e $OUT_ERRORS -o $OUT_ERRORS exec_jtkt_$comment
	#qsub -V -t 1-$noFileToRun -S /bin/tcsh -r y -e $OUT_ERRORS -o $OUT_ERRORS exec_jtkt_$comment
    #sbatch -v --array=1-9 exec_jtkt_$comment -J $comment  -e $OUT_ERRORS/slurm-%A_%a.out -o $OUT_ERRORS/slurm-%A_%a.out
    sbatch -v --array=1-$noFileToRun exec_jtkt_$comment -J $comment  -e $OUT_ERRORS/slurm-%A_%a.out -o $OUT_ERRORS/slurm-%A_%a.out
